FROM jetbrains/teamcity-agent:2018.1-windowsservercore
# USER ContainerAdministrator
# RUN wget https://download.sonatype.com/clm/scanner/latest.jar -UseBasicParsing -OutFile "C:\Users\ContainerUser\nexus-cli.jar";
# USER ConatainerUser