version: '3.9'

services:

  nxiq:
    image: "sonatype/nexus-iq-server:1.155.0"
    ports:
      - "8070:8070"
    volumes:
      - "../../config/nexus-iq-config.yaml:/etc/nexus-iq-server/config.yml:delegated"
      - "./data/iq-data:/sonatype-work:delegated"
      - "./data/iq-logs:/opt/sonatype/nexus-iq-server/log:delegated"
